package BimsS.Absyn; // Java Package generated by the BNF Converter.

public abstract class AExp implements java.io.Serializable {
  public abstract <R,A> R accept(AExp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(BimsS.Absyn.APlus p, A arg);
    public R visit(BimsS.Absyn.AMinus p, A arg);
    public R visit(BimsS.Absyn.ATimes p, A arg);
    public R visit(BimsS.Absyn.AVar p, A arg);
    public R visit(BimsS.Absyn.AInt p, A arg);

  }

}
