package BimsS.Absyn; // Java Package generated by the BNF Converter.

public class AVar extends AExp {
  public final Var var_;
  public AVar(Var p1) { var_ = p1; }

  public <R,A> R accept(BimsS.Absyn.AExp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof BimsS.Absyn.AVar) {
      BimsS.Absyn.AVar x = (BimsS.Absyn.AVar)o;
      return this.var_.equals(x.var_);
    }
    return false;
  }

  public int hashCode() {
    return this.var_.hashCode();
  }


}
