package BimsS.Absyn; // Java Package generated by the BNF Converter.

public class BAnd extends BExp {
  public final BExp bexp_1, bexp_2;
  public BAnd(BExp p1, BExp p2) { bexp_1 = p1; bexp_2 = p2; }

  public <R,A> R accept(BimsS.Absyn.BExp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof BimsS.Absyn.BAnd) {
      BimsS.Absyn.BAnd x = (BimsS.Absyn.BAnd)o;
      return this.bexp_1.equals(x.bexp_1) && this.bexp_2.equals(x.bexp_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.bexp_1.hashCode())+this.bexp_2.hashCode();
  }


}
