package BimsS.Absyn; // Java Package generated by the BNF Converter.

public abstract class BExp implements java.io.Serializable {
  public abstract <R,A> R accept(BExp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(BimsS.Absyn.BEq p, A arg);
    public R visit(BimsS.Absyn.BGt p, A arg);
    public R visit(BimsS.Absyn.BNeg p, A arg);
    public R visit(BimsS.Absyn.BAnd p, A arg);

  }

}
