package BimsS.Absyn; // Java Package generated by the BNF Converter.

public class SIf extends Stm {
  public final BExp bexp_;
  public final ListStm liststm_1, liststm_2;
  public SIf(BExp p1, ListStm p2, ListStm p3) { bexp_ = p1; liststm_1 = p2; liststm_2 = p3; }

  public <R,A> R accept(BimsS.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof BimsS.Absyn.SIf) {
      BimsS.Absyn.SIf x = (BimsS.Absyn.SIf)o;
      return this.bexp_.equals(x.bexp_) && this.liststm_1.equals(x.liststm_1) && this.liststm_2.equals(x.liststm_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.bexp_.hashCode())+this.liststm_1.hashCode())+this.liststm_2.hashCode();
  }


}
