package BimsS.Absyn; // Java Package generated by the BNF Converter.

public class SIntArr extends Stm {
  public final String ident_;
  public final AExp aexp_;
  public SIntArr(String p1, AExp p2) { ident_ = p1; aexp_ = p2; }

  public <R,A> R accept(BimsS.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof BimsS.Absyn.SIntArr) {
      BimsS.Absyn.SIntArr x = (BimsS.Absyn.SIntArr)o;
      return this.ident_.equals(x.ident_) && this.aexp_.equals(x.aexp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.aexp_.hashCode();
  }


}
