package BimsS.Absyn; // Java Package generated by the BNF Converter.

public class SPrint extends Stm {
  public final Var var_;
  public SPrint(Var p1) { var_ = p1; }

  public <R,A> R accept(BimsS.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof BimsS.Absyn.SPrint) {
      BimsS.Absyn.SPrint x = (BimsS.Absyn.SPrint)o;
      return this.var_.equals(x.var_);
    }
    return false;
  }

  public int hashCode() {
    return this.var_.hashCode();
  }


}
