package BimsS.Absyn; // Java Package generated by the BNF Converter.

public class SSkip extends Stm {
  public SSkip() { }

  public <R,A> R accept(BimsS.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof BimsS.Absyn.SSkip) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
