package BimsS.Absyn; // Java Package generated by the BNF Converter.

public abstract class Stm implements java.io.Serializable {
  public abstract <R,A> R accept(Stm.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(BimsS.Absyn.SAss p, A arg);
    public R visit(BimsS.Absyn.SSkip p, A arg);
    public R visit(BimsS.Absyn.SIf p, A arg);
    public R visit(BimsS.Absyn.SWhile p, A arg);
    public R visit(BimsS.Absyn.SPrint p, A arg);
    public R visit(BimsS.Absyn.SInt p, A arg);
    public R visit(BimsS.Absyn.SIntArr p, A arg);

  }

}
