package BimsS.Absyn; // Java Package generated by the BNF Converter.

public class SWhile extends Stm {
  public final BExp bexp_;
  public final ListStm liststm_;
  public SWhile(BExp p1, ListStm p2) { bexp_ = p1; liststm_ = p2; }

  public <R,A> R accept(BimsS.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof BimsS.Absyn.SWhile) {
      BimsS.Absyn.SWhile x = (BimsS.Absyn.SWhile)o;
      return this.bexp_.equals(x.bexp_) && this.liststm_.equals(x.liststm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.bexp_.hashCode())+this.liststm_.hashCode();
  }


}
